"use client";
import { useEffect, useRef, useState } from "react";
import type { EditorialPost } from "@/lib/research/editorial-posts";
import { weeklyHeadings } from "@/lib/research/weekly";
import styles from "./styles.module.css";
const blank = () => ({id:crypto.randomUUID(),version:0,kind:"weekly",status:"draft",titleJa:"",titleEn:"",introJa:"",introEn:"",bodyJa:weeklyHeadings.map(t=>`## ${t}\n`).join("\n"),bodyEn:"",sources:[] as {title:string;url:string}[]});
type Draft=ReturnType<typeof blank>;
export default function WeeklyComposer({onPublished}:{onPublished:()=>void}) {
 const [draft,setDraft]=useState<Draft|null>(null),[items,setItems]=useState<EditorialPost[]>([]),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[verified,setVerified]=useState(false),[message,setMessage]=useState(""),[sourcesText,setSourcesText]=useState(""),[nextOffset,setNextOffset]=useState<number|null>(null);
 const flight=useRef(false);
 useEffect(()=>{setDraft(blank());const c=new AbortController();fetch('/api/research/weekly-author',{cache:'no-store',signal:c.signal}).then(r=>r.json()).then(d=>{if(c.signal.aborted)return;if(d.ok){setItems(d.items);setNextOffset(d.nextOffset??null);}else setMessage(d.error==='setup-required'?'週刊の保存用キーがサーバーに設定されていません。':d.error==='owner-required'?'運営者としてログインしてください。':'週刊の保存サービスに接続できません。');}).catch(()=>{if(!c.signal.aborted)setMessage('下書きを読み込めませんでした。');});return()=>c.abort();},[]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>e.preventDefault();window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 useEffect(()=>{if(!draft?.version||draft.bodyEn||dirty||draft.status!=='draft')return;const c=new AbortController();let pending=false;const timer=setInterval(async()=>{if(pending||document.hidden)return;pending=true;try{const r=await fetch('/api/research/weekly-author',{cache:'no-store',signal:AbortSignal.any([c.signal,AbortSignal.timeout(15000)])});const d=await r.json();if(c.signal.aborted)return;const found=d.items?.find((v:EditorialPost)=>v.id===draft.id);if(found?.bodyEn){setDraft(found);setItems(d.items);setMessage('英語版ができました。');}}catch{}finally{pending=false;}},8000);return()=>{clearInterval(timer);c.abort();};},[draft,dirty]);
 const change=(patch:Partial<Draft>)=>{setDraft(d=>d?{...d,...patch}:d);setDirty(true);setVerified(false);};
 async function older(){if(nextOffset===null||flight.current)return;flight.current=true;setBusy(true);try{const r=await fetch(`/api/research/weekly-author?offset=${nextOffset}`,{cache:'no-store',signal:AbortSignal.timeout(15000)});const d=await r.json();if(!r.ok||!d.ok)throw Error();setItems(v=>[...v,...d.items.filter((i:EditorialPost)=>!v.some(x=>x.id===i.id))]);setNextOffset(d.nextOffset??null);}catch{setMessage('履歴を読み込めませんでした。');}finally{flight.current=false;setBusy(false);}}
 async function save(action:'draft'|'publish'|'withdraw') {if(!draft||flight.current)return;flight.current=true;setBusy(true);setMessage('');try{const r=await fetch('/api/research/weekly-author',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...draft,action,verified}),signal:AbortSignal.timeout(45000)});const d=await r.json();if(d.item){setDraft(d.item);setItems(v=>[d.item,...v.filter(x=>x.id!==d.item.id)]);setDirty(false);}if(!r.ok||!d.ok)throw Error(d.error);setVerified(false);setMessage(action==='draft'?'下書きを保存しました。英語版を作成します。':action==='publish'?'公開しました。':'公開を取り下げました。');if(action!=='draft')onPublished();}catch{setMessage('完了できませんでした。入力を残しています。英語版・出典・接続を確認してください。');}finally{flight.current=false;setBusy(false);}}
 if(!draft)return null;
 const ready=!!draft.titleEn&&!!draft.introEn&&!!draft.bodyEn&&!dirty;
 return <details className={styles.composer}><summary>週刊を書く・編集する</summary><form onSubmit={e=>{e.preventDefault();void save('draft');}} aria-busy={busy}>
 {draft.status==='published'&&<p>編集して保存すると下書きに戻ります。</p>}<fieldset disabled={busy}><label>タイトル<input value={draft.titleJa} maxLength={180} onChange={e=>change({titleJa:e.target.value})}/></label><label>今週の要点<textarea rows={2} value={draft.introJa} maxLength={500} onChange={e=>change({introJa:e.target.value})}/></label><label>本文<textarea className={styles.body} value={draft.bodyJa} maxLength={6000} onChange={e=>change({bodyJa:e.target.value})}/></label>
 <label>出典（1行に「資料名 | URL」）<textarea rows={2} maxLength={8000} value={sourcesText} onChange={e=>{setSourcesText(e.target.value);change({sources:e.target.value.split('\n').filter(Boolean).map(line=>{const i=line.indexOf('|');return{title:i<0?line:line.slice(0,i).trim(),url:i<0?'':line.slice(i+1).trim()};})});}}/></label></fieldset>
 <div className={styles.actions}><button type="submit" disabled={busy||!draft.titleJa.trim()||!draft.introJa.trim()||!draft.bodyJa.trim()}>下書き保存</button><button type="button" disabled={busy||dirty} onClick={()=>{setDraft(blank());setSourcesText('');setVerified(false);setMessage('');}}>新しく書く</button></div>
 {ready&&<details><summary>英語版を確認</summary><h3>{draft.titleEn}</h3><p>{draft.introEn}</p><div className={styles.english}>{draft.bodyEn}</div></details>}
 <label className={styles.check}><input type="checkbox" checked={verified} disabled={!ready||busy} onChange={e=>setVerified(e.target.checked)}/>内容と出典を確認した</label>
 <div className={styles.actions}><button type="button" disabled={busy||!ready||!verified||!draft.sources.length} onClick={()=>void save('publish')}>公開する</button>{draft.status==='published'&&<button type="button" disabled={busy||dirty} onClick={()=>void save('withdraw')}>公開を取り下げる</button>}</div>
 {message&&<p role="status">{message}</p>}
 {(items.length>0||nextOffset!==null)&&<details><summary>過去の週刊・下書き</summary>{items.map(i=><button type="button" key={i.id} disabled={busy||dirty} onClick={()=>{setDraft(i);setSourcesText(i.sources.map(s=>`${s.title} | ${s.url}`).join('\n'));setVerified(false);setMessage('');}}>{i.titleJa||'無題'} · {i.status==='published'?'公開中':'下書き'}</button>)}{nextOffset!==null&&<button type="button" disabled={busy} onClick={()=>void older()}>以前の週刊を表示</button>}</details>}
 </form></details>;
}
